
export default [
  {
    id: 1,
    img: "review-1.svg",
    job: "Google",
    time: "2 ",
    star: 5,
    name: "Tobi Bakare ",
    description: "Et nesciunt expedita aut enim obcaecati sit omnis magnam est numquam iure ut commodi dolorem.Et molestiae Et nesciunt expedita aut enim obcaecati sit omnis magnamest numquam iure ut commodi dolorem. Et molestiae ",
  },
  {
    id: 2,
    img: "review-2.svg",
    job: "DHL",
    time: "1 ",
    star: 5,
    name: "Adesuwa Ighodaro",
    description: "Et nesciunt expedita aut enim obcaecati sit omnis magnam est numquam iure ut commodi dolorem.Et molestiae Et nesciunt expedita aut enim obcaecati sit omnis magnamest numquam iure ut commodi dolorem. Et molestiae ",
  },
  {
    id: 3,
    img: "review-3.svg",
    job: "Meta",
    time: "3 ",
    star: 5,
    name: "Amarachi Nwosu",
    description: "Et nesciunt expedita aut enim obcaecati sit omnis magnam est numquam iure ut commodi dolorem.Et molestiae Et nesciunt expedita aut enim obcaecati sit omnis magnamest numquam iure ut commodi dolorem. Et molestiae ",
  },
  {
    id: 4,
    img: "review-4.svg",
    job: "Google",
    time: "2 ",
    star: 5,
    name: "Ngozi Obi ",
    description: "Et nesciunt expedita aut enim obcaecati sit omnis magnam est numquam iure ut commodi dolorem.Et molestiae Et nesciunt expedita aut enim obcaecati sit omnis magnamest numquam iure ut commodi dolorem. Et molestiae ",
  },
  {
    id: 5,
    img: "review-5.svg",
    job: "Meta",
    time: "1 ",
    star: 5,
    name: "Chukwudi Okafor ",
    description: "Et nesciunt expedita aut enim obcaecati sit omnis magnam est numquam iure ut commodi dolorem.Et molestiae Et nesciunt expedita aut enim obcaecati sit omnis magnamest numquam iure ut commodi dolorem. Et molestiae ",
  },
  {
    id: 6,
    img: "review-6.svg",
    job: "Mircosoft",
    time: "4 ",
    star: 5,
    name: "Adebayo Adeyemi ",
    description: "Et nesciunt expedita aut enim obcaecati sit omnis magnam est numquam iure ut commodi dolorem.Et molestiae Et nesciunt expedita aut enim obcaecati sit omnis magnamest numquam iure ut commodi dolorem. Et molestiae ",
  },
]